### ISSUE TITLE
你好,这个键盘为什么在iOS端很卡呢?

### ISSUE THREAD

**Issue by 1409004379** [yujinjin/vue-number-keyboard#2]

**Comment by yujinjin** [comment]
@1409004379 是直接运行的demo就发现很卡吗？

**Comment by 1409004379** [comment]
您好,非常感谢您的回复,现在的情况是放在demo里运行没有问题,但是放入iOS,使用webview加载就会特别卡,请问是什么原因?




------------------ 原始邮件 ------------------
发件人: "yujinjin"<notifications@github.com>;
发送时间: 2019年8月23日(星期五) 下午3:17
收件人: "yujinjin/vue-number-keyboard"<vue-number-keyboard@noreply.github.com>;
抄送: "YOU 龍"<1409004379@qq.com>;"Mention"<mention@noreply.github.com>;
主题: Re: [yujinjin/vue-number-keyboard] 你好,这个键盘为什么在iOS端很卡呢? (#2)




@1409004379 是直接运行的demo就发现很卡吗？

**Comment by yujinjin** [comment]
@1409004379 这个插件的代码很简单，都是普通的html、css。非要说卡顿的话只能怀疑你的手机对css3的动画transform支持很差。

**Comment by 1409004379** [comment]
你好,这个卡顿问题是会在iOS手机上出现的,我的解决办法是引入了一个fastClick的依赖,希望能帮到有相似问题的人

**Comment by yujinjin** [comment]
@1409004379 如果是这样的话，其实不是组件的卡顿问题，是iOS的click事件延迟300ms导致
